# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tutor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Ringle
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
'RCTText',
'RCTImage',
'RCTNetwork',
'RCTWebSocket',
'Core',

]

pod 'react-native-opentok', :path => '../react-native-opentok'
pod 'Firebase/Messaging'
pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'


end
